export const sympTomDiease = [
  {
    id: "1",
    name: "Mồ hôi dầu, hôi nách",
    root: "thường bị thấp nhiệt trong người",
  },
  {
    id: "2",
    name: "Ấn đường (chính giữa hai chân lông mày) u ám",
    root:
      "khí huyết lưu thông không tốt, dễ bị các kích xúc bên ngoài. Báo hiệu sắp có họa xảy ra trong đó có sức khỏe",
  },
  {
    id: "3",
    name: "Mùi cơ thể quá thơm",
    root: "cẩn thận tỳ (lá lách) sắp tuyệt",
  },
  {
    id: "4",
    name: "Mùi cơ thể quá thối",
    root: "cẩn thận có bệnh dạ dày, nặng có thể ung thư dạ dày",
  },
  { id: "5", name: "Hay nằm sấp", root: "thường có bệnh đường tiêu hóa" },
  {
    id: "6",
    name: "Trẻ con có đường nổi giữa trán",
    root:
      "đừng ngại vì đó là dấu hiệu thông minh do máu lên não, lưu thông tốt",
  },
  {
    id: "7",
    name: "Hay chảy máu chân răng, lợi đỏ",
    root: "thường dạ dày nóng",
  },
  { id: "8", name: "Hơi thở mùi thối khẳn", root: "dạ dày nóng" },
  { id: "9", name: "Hơi thở có mùi chua", root: "dạ dày lạnh" },
  { id: "10", name: "Hay tức giận,mắt đỏ,nhiều rỉ mắt", root: "gan nóng" },
  {
    id: "11",
    name: "Hay chảy nước mắt",
    root: "dễ xúc động gan và thận bị lạnh",
  },
  { id: "12", name: "Hay trầm uất lo nghĩ", root: "lá lách kém" },
  { id: "13", name: "Tai ù tai điếc", root: "do khí huyết bị tắc thận kém" },
  { id: "14", name: "Hay bị cảm", root: "dương khí hư lỗ chân lông mở" },
  { id: "15", name: "Rìa lưỡi có nhiều nốt đỏ", root: "gan nóng tích độc" },
  { id: "16", name: "Môi nhợt", root: "máu lưu thông kém" },
  { id: "17", name: "Môi đỏ quá mức", root: "tim và lá lách nóng" },
  { id: "18", name: "Đại tiện phân sống", root: "lá lách và thận lạnh" },
  {
    id: "19",
    name: "Đại tiện phân đen như rau để qua đêm",
    root: "bị xuất huyết hệ tiêu hoá",
  },
  {
    id: "20",
    name: "Bị tiêu chảy phân vàng nhiều bọt",
    root: "không phải bị lạnh mà bị nóng quá",
  },
  { id: "21", name: "Nước tiểu vàng", root: "người khô nóng" },
  { id: "22", name: "Nước tiểu trong", root: "thận bị lạnh" },
  { id: "23", name: "Hay bị đi tiểu đêm", root: "thận khí hư" },
  { id: "24", name: "Hay đau bụng đi ngoài buổi sáng", root: "thận bị lạnh" },
  { id: "25", name: "Tai chảy mủ", root: "tim bị nóng" },
  {
    id: "26",
    name: "Hay quên lơ đễnh",
    root: "tim và thận phối hợp làm việc không được tốt thiếu tinh chất",
  },
  { id: "27", name: "Đờm trắng nước mũi trong", root: "phổi bị lạn" },
  { id: "28", name: "Phụ nữ đầu mũi đo", root: "tử cung bị xung huyế" },
  {
    id: "29",
    name: "Cơ thể cảm thấy trên nóng dưới lạnh hoặc trên nặng dưới nhẹ",
    root: "do thận dương hư",
  },
  { id: "30", name: "Quầng mắt thâm đen", root: "thận hư tinh lực thiếu hụt" },
  { id: "31", name: "Hay ra mồ hôi trộm", root: "người nóng quá" },
  {
    id: "32",
    name: "Mồ hôi ra ban ngày khi thức lại có mùi chua",
    root: "người lạnh quá",
  },
  { id: "33", name: "Gót chân khô nứt", root: "thận khô thiếu dưỡng chất" },
  {
    id: "34",
    name: "Bàn chân nóng rát",
    root: "thận hư cẩn thận tiểu đường huyết áp",
  },
  {
    id: "35",
    name: "Bàn tay lạnh nhiều mồ hôi tay",
    root: "do lá lách lạnh quá",
  },
  { id: "36", name: "Lông mày rụng nhiều", root: "phổi và thận khí hư" },
  {
    id: "37",
    name: "Tóc bạc",
    root: "thận khí hư hoặc máu xấu, thần kinh suy nhược",
  },
  {
    id: "38",
    name: "Chóng đói người không béo được dù ăn nhiều",
    root: "do dạ dày nóng quá",
  },
  { id: "39", name: "Người phù tích nước", root: "thận và lá lách đã hư" },
  {
    id: "40",
    name: "Bụng phình to chân tay teo nhẽo",
    root: "gan đã bị xơ lá lách sắp ngừng hoạt động",
  },
  { id: "41", name: "Chân bị phù", root: "là thận hư" },
];
