export const sympTomDiease = [
  {
    id: "1",
    name: "Mồ hôi dầu, hôi nách",
    root: "thường bị thấp nhiệt trong người",
  },
  {
    id: "2",
    name: "Ấn đường (chính giữa hai chân lông mày) u ám",
    root:
      "khí huyết lưu thông không tốt, dễ bị các kích xúc bên ngoài. Báo hiệu sắp có họa xảy ra trong đó có sức khỏe",
  },
  {
    id: "3",
    name: "Mùi cơ thể quá thơm",
    root: "cẩn thận tỳ (lá lách) sắp tuyệt",
  },
  {
    id: "4",
    name: "Mùi cơ thể quá thối",
    root: "cẩn thận có bệnh dạ dày, nặng có thể ung thư dạ dày",
  },
  { id: "5", name: "Hay nằm sấp", root: "thường có bệnh đường tiêu hóa" },
  {
    id: "6",
    name: "Trẻ con có đường nổi giữa trán",
    root:
      "đừng ngại vì đó là dấu hiệu thông minh do máu lên não, lưu thông tốt",
  },
  {
    id: "7",
    name: "Hay chảy máu chân răng, lợi đỏ",
    root: "thường dạ dày nóng",
  },
  { id: "8", name: "Hơi thở mùi thối khẳn", root: "dạ dày nóng" },
  { id: "9", name: "Hơi thở có mùi chua", root: "dạ dày lạnh" },
  { id: "10", name: "Hay tức giận,mắt đỏ,nhiều rỉ mắt", root: "gan nóng" },
  {
    id: "11",
    name: "Hay chảy nước mắt",
    root: "dễ xúc động gan và thận bị lạnh",
  },
  { id: "12", name: "Hay trầm uất lo nghĩ", root: "lá lách kém" },
  { id: "13", name: "Tai ù tai điếc", root: "do khí huyết bị tắc thận kém" },
  { id: "14", name: "Hay bị cảm", root: "dương khí hư lỗ chân lông mở" },
  { id: "15", name: "Rìa lưỡi có nhiều nốt đỏ", root: "gan nóng tích độc" },
  { id: "16", name: "Môi nhợt", root: "máu lưu thông kém" },
  { id: "17", name: "Môi đỏ quá mức", root: "tim và lá lách nóng" },
  { id: "18", name: "Đại tiện phân sống", root: "lá lách và thận lạnh" },
  {
    id: "19",
    name: "Đại tiện phân đen như rau để qua đêm",
    root: "bị xuất huyết hệ tiêu hoá",
  },
  {
    id: "20",
    name: "Bị tiêu chảy phân vàng nhiều bọt",
    root: "không phải bị lạnh mà bị nóng quá",
  },
  { id: "21", name: "Nước tiểu vàng", root: "người khô nóng" },
  { id: "22", name: "Nước tiểu trong", root: "thận bị lạnh" },
  { id: "23", name: "Hay bị đi tiểu đêm", root: "thận khí hư" },
  { id: "24", name: "Hay đau bụng đi ngoài buổi sáng", root: "thận bị lạnh" },
  { id: "25", name: "Tai chảy mủ", root: "tim bị nóng" },
  {
    id: "26",
    name: "Hay quên lơ đễnh",
    root: "tim và thận phối hợp làm việc không được tốt thiếu tinh chất",
  },
  { id: "27", name: "Đờm trắng nước mũi trong", root: "phổi bị lạn" },
  { id: "28", name: "Phụ nữ đầu mũi đo", root: "tử cung bị xung huyế" },
  {
    id: "29",
    name: "Cơ thể cảm thấy trên nóng dưới lạnh hoặc trên nặng dưới nhẹ",
    root: "do thận dương hư",
  },
  { id: "30", name: "Quầng mắt thâm đen", root: "thận hư tinh lực thiếu hụt" },
  { id: "31", name: "Hay ra mồ hôi trộm", root: "người nóng quá" },
  {
    id: "32",
    name: "Mồ hôi ra ban ngày khi thức lại có mùi chua",
    root: "người lạnh quá",
  },
  { id: "33", name: "Gót chân khô nứt", root: "thận khô thiếu dưỡng chất" },
  {
    id: "34",
    name: "Bàn chân nóng rát",
    root: "thận hư cẩn thận tiểu đường huyết áp",
  },
  {
    id: "35",
    name: "Bàn tay lạnh nhiều mồ hôi tay",
    root: "do lá lách lạnh quá",
  },
  { id: "36", name: "Lông mày rụng nhiều", root: "phổi và thận khí hư" },
  {
    id: "37",
    name: "Tóc bạc",
    root: "thận khí hư hoặc máu xấu, thần kinh suy nhược",
  },
  {
    id: "38",
    name: "Chóng đói người không béo được dù ăn nhiều",
    root: "do dạ dày nóng quá",
  },
  { id: "39", name: "Người phù tích nước", root: "thận và lá lách đã hư" },
  {
    id: "40",
    name: "Bụng phình to chân tay teo nhẽo",
    root: "gan đã bị xơ lá lách sắp ngừng hoạt động",
  },
  { id: "41", name: "Chân bị phù", root: "là thận hư" },
];

export const normalizedSymtomDisease = [
  {
    id: "1",
    name: "Mo hoi dau, hoi nach",
    root: "thuong bi thap nhiet trong nguoi",
  },
  {
    id: "2",
    name: "An duong (chinh giua hai chan long may) u am",
    root:
      "khi huyet luu thong khong tot, de bi cac kich xuc ben ngoai. Bao hieu sap co hoa xay ra trong do co suc khoe",
  },
  {
    id: "3",
    name: "Mui co the qua thom",
    root: "can than ty (la lach) sap tuyet",
  },
  {
    id: "4",
    name: "Mui co the qua thoi",
    root: "can than co benh da day, nang co the ung thu da day",
  },
  { id: "5", name: "Hay nam sap", root: "thuong co benh duong tieu hoa" },
  {
    id: "6",
    name: "Tre con co duong noi giua tran",
    root:
      "dung ngai vi do la dau hieu thong minh do mau len nao, luu thong tot",
  },
  {
    id: "7",
    name: "Hay chay mau chan rang, loi do",
    root: "thuong da day nong",
  },
  { id: "8", name: "Hoi tho mui thoi khan", root: "da day nong" },
  { id: "9", name: "Hoi tho co mui chua", root: "da day lanh" },
  { id: "10", name: "Hay tuc gian,mat do,nhieu ri mat", root: "gan nong" },
  {
    id: "11",
    name: "Hay chay nuoc mat",
    root: "de xuc dong gan va than bi lanh",
  },
  { id: "12", name: "Hay tram uat lo nghi", root: "la lach kem" },
  { id: "13", name: "Tai u tai diec", root: "do khi huyet bi tac than kem" },
  { id: "14", name: "Hay bi cam", root: "duong khi hu lo chan long mo" },
  { id: "15", name: "Ria luoi co nhieu not do", root: "gan nong tich doc" },
  { id: "16", name: "Moi nhot", root: "mau luu thong kem" },
  { id: "17", name: "Moi do qua muc", root: "tim va la lach nong" },
  { id: "18", name: "Dai tien phan song", root: "la lach va than lanh" },
  {
    id: "19",
    name: "Dai tien phan den nhu rau de qua dem",
    root: "bi xuat huyet he tieu hoa",
  },
  {
    id: "20",
    name: "Bi tieu chay phan vang nhieu bot",
    root: "khong phai bi lanh ma bi nong qua",
  },
  { id: "21", name: "Nuoc tieu vang", root: "nguoi kho nong" },
  { id: "22", name: "Nuoc tieu trong", root: "than bi lanh" },
  { id: "23", name: "Hay bi di tieu dem", root: "than khi hu" },
  { id: "24", name: "Hay dau bung di ngoai buoi sang", root: "than bi lanh" },
  { id: "25", name: "Tai chay mu", root: "tim bi nong" },
  {
    id: "26",
    name: "Hay quen lo denh",
    root: "tim va than phoi hop lam viec khong duoc tot thieu tinh chat",
  },
  { id: "27", name: "Dom trang nuoc mui trong", root: "phoi bi lan" },
  { id: "28", name: "Phu nu dau mui do", root: "tu cung bi xung huye" },
  {
    id: "29",
    name: "Co the cam thay tren nong duoi lanh hoac tren nang duoi nhe",
    root: "do than duong hu",
  },
  { id: "30", name: "Quang mat tham den", root: "than hu tinh luc thieu hut" },
  { id: "31", name: "Hay ra mo hoi trom", root: "nguoi nong qua" },
  {
    id: "32",
    name: "Mo hoi ra ban ngay khi thuc lai co mui chua",
    root: "nguoi lanh qua",
  },
  { id: "33", name: "Got chan kho nut", root: "than kho thieu duong chat" },
  {
    id: "34",
    name: "Ban chan nong rat",
    root: "than hu can than tieu duong huyet ap",
  },
  {
    id: "35",
    name: "Ban tay lanh nhieu mo hoi tay",
    root: "do la lach lanh qua",
  },
  { id: "36", name: "Long may rung nhieu", root: "phoi va than khi hu" },
  {
    id: "37",
    name: "Toc bac",
    root: "than khi hu hoac mau xau, than kinh suy nhuoc",
  },
  {
    id: "38",
    name: "Chong doi nguoi khong beo duoc du an nhieu",
    root: "do da day nong qua",
  },
  { id: "39", name: "Nguoi phu tich nuoc", root: "than va la lach da hu" },
  {
    id: "40",
    name: "Bung phinh to chan tay teo nheo",
    root: "gan da bi xo la lach sap ngung hoat dong",
  },
  { id: "41", name: "Chan bi phu", root: "la than hu" },
];
